### PR TITLE
Simple Comment Editing Integration

### PR DESCRIPTION
**Pull request by ronalfy**
Hi, I tried to leave useful commits. Please let me know if you have any questions.

Major changes:
1. Added two events to epoch.js for when a new comment is posted and when comments are loaded.
2. Added DOING_AJAX constant to classes/front/api_process.php so other devs can check whether they are in an AJAX request or not.
3. Added additional passed argument to classes/front/api_helper.php to add context to the comment_text filter so you can know which comment you are on.
4. Updated the minified JS.

To Test (I used the 2012 theme and also Cover https://wordpress.org/themes/cover/):
1.  Install this branch (assuming you have included the vendor directory).
2.  Install the latest from https://github.com/ronalfy/simple-comment-editing
3.  Leave a comment and you should see the editing interface below the new comment text.
4.  Refresh the page, let the comments load, and you should see the editing interface below the new coment text.

I tested this on three views using WordPress 4.3.

### CODE REVIEW

**Comment by Shelob9** [comment]
This was closed because I deleted the branch, not because we do not want the PR (looks cool.)

**Comment by Shelob9** [comment]
@ronalfy 

First off, Jason showed me the demo of this, and it was super awesome. I love it.

I can see why you assumed that you should submit against 1.0.2-dev branch, I really should publish clear contributors guidelines, and I should have done everything that was in that in another branch, since everything there was for a feature that got punted to 1.0.3 and is going to take more time. Semantics aside, this PR, which I want really should get branched directly off master so it can be more cleanly merged.

So I hope you can resubmit against master, and I'll make it work for an upcoming release.

Here is my actual feedback on the PR:

1) It was a conscious decision on my part not to define `DOING_AJAX` in our API. In my opinion, that constant should mean that admin-ajax endpoint is in use, which it is not in this case. Obviously this is confusing, there is no right answer, and is why we need a standard for front-end AJAX, instead of doing these kinds of custom APIs (hopefully the REST API will be in core soon.) But I digress...

Feel free to disagree with me here -- I'm often wrong -- or say "hey Josh, I need someway, besides checking for the query var `epoch-api` to know Epoch API is happening.

Speaking of which:
2) Your system uses the admin-ajax endpoint. This concerns me as part of the reason we're using our own API is that means all of our AJAX passes through one independent point, whose URL is filterable. This opens up the possibility of proxying the API so a separate server can act as a comment cache, which would enable this to be used on high traffic sites.

That means that this integration may not work if/when we get that set up. I'm not sure how decoupled you admin-ajax handler is from your actual logic for editing comments. Is it possible we could route the inline editing through the epoch api when doing inline edits?

3) Adding comment object to our reuse of `comment_text` filter is smart, wondering if we can get the thrid arg in there too...

4) Adding that handler in our JS, very smart as well.

**Comment by ronalfy** [comment]
1. Thanks. Can we do a EPOCH_AJAX or something similar instead?
2. Not sure I can get away from admin-ajax.php. It looks like your comment was cut off. Can you re-post and I'll see if it's doable. 

3,4: gracias

**Comment by Shelob9** [comment]
@ronalfy 

1) Can I ask why that's preferable to checking the query var?

2) I updated it. Was asking if this can get optionally routed through Epoch API.

**Comment by ronalfy** [comment]
Thanks.
1. No need to do an isset check and eval, just a defined check. I can work
   with a query var though, no biggie.

**Comment by Shelob9** [comment]
1. Fair enough. There will be `EPOCH_API` in version 1.0.2.

BTW 1.0.2 is going to be really minor and will be out quite soon. If you resubmit this against master, we can look at it for 1.0.3, which is turning into the bigger update, and will probably be a 1.1.0.

**Comment by ronalfy** [comment]
@Shelob9 do you still want me to do a pull request on master? I see there are still changes being committed against this branch.

**Comment by Shelob9** [comment]
This branch was supposed to be deleted after getting renamed. It really should have been a feature branch. I need to devise/ publish a git workflow for this. But yes, please do submit against master, I'll merge it after 1.0.2 is released.

**Comment by ronalfy** [comment]
Thanks. I submitted a new request. Thanks for the help.

**Comment by Vernal** [comment]
Awesome resolution you guys. Thanks to you both for being brilliant.

**Pull request closed without merging**
